config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :contacts, only: [:new, :create]
  post '/sendform', to: 'contacts#sendmail'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, :validate => true
	attribute :email, :validate =>  /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	attribute :message, :validate => true

	def headers 
		{
			:subject => "Support Form",
			:to => "kasatkin1998andriy@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :new
		end
	end

	def sendmail
		@name = params[:user][:name]
		@email = params[:user][:email]
		@message = params[:user][:message]
		UserMailer.contact_form(@name, @email, @message).deliver_later
		flash.now[:success] = "Email was sended! Success!"
		redirect_to root_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/create.html.erb
<h1>Say Hello!</h1>
<div>
	<h1>Thank you for your message!</h1>
	<p>We send you in email</p>
</div>

app/views/contacts/new.html.erb
<!--////////////////////////////////////Container-->
		<section id="container">
			<div class="wrap-container clearfix">
				<div id="main-content">
					<div class="wrap-content zerogrid ">
						<article class="background-gray">
							<div class="art-header">
								<h6>If you have any problems fill out the form we will help you as soon as possible!</h6>
								<hr class="line-2">
								<h2>Contact form</h2>
							</div>
							<div class="art-content">
								<div class="row">
									<div id="contact_form">
										<%= form_for :user, url: {action: "sendmail"}, html: {id: "ff"} do |f| %>
											<label class="row">
												<div class="col-1-2">
													<div class="wrap-col">
														<%= f.text_field :name, id: "name", required: true,  placeholder: "Enter name" %>
													</div>
												</div>
												<div class="col-1-2">
													<div class="wrap-col">
														<%= f.email_field :email,  id: "email", required: true,  placeholder: "Enter email" %>
													</div>
												</div>
											</label>
											<label class="row">
												<div class="wrap-col">
													<%= f.text_area :message, id: "message", class: "form-control", required: true, as: :text, cols: "25", rows: "4",placeholder: "Describe the problem" %>
												</div>
											</label>
											<center><%= f.submit 'Send Message', class: "button sendButton" %></center>
										<% end %>
									</div>
								</div>
							</div>
						</article>
					</div>
				</div>
			</div>
		</section>

app/views/home/index.html.erb
<!--////////////////////////////////////Container-->
		<section id="container">
			<div class="wrap-container">
				<!-----------------content-box-1-------------------->
				<section class="content-box background-gray box-1 zerogrid">
					<div class="row wrap-box"><!--Start Box-->
						<div class="col-1-2">
							<div class="wrap-col">
								<div style="padding-top: 60px;">
									<center><%= image_tag("4.png") %></center>
								</div>
							</div>
						</div>
						<div class="col-1-2">
							<div class="wrap-col">
								<div class="row">
									<div class="t-center" style="padding-top: 30px;">
										<div class="header">
											<h2>Delicious  <span class="color-red">meat</span></h2>
										</div>
										<strong>BECIEGAST NVERITI VITAESAERT ASETY KERTYA ASET APLICA BOSERDE NERAFAE KERTYURAUAS VITAESA. </strong><br/><br>
										<span>Praesent vestibulum aenean nonummy endrerit mauris. Cum sociis natoque Magnis dis parturient montes. Ascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio gravida at cursus nec luctus a lorem.</span><br/><br>
										<a href="#" class="button" >More Details</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
				<!-----------------content-box-2-------------------->
				<section class="content-box background-white box-2 zerogrid">
					<div class="row wrap-box"><!--Start Box-->
						<div class="col-1-2 f-right">
							<div class="wrap-col">
								<div style="padding-top: 60px;">
									<center><%= image_tag("3.png") %></center>
								</div>
							</div>
						</div>
						<div class="col-1-2">
							<div class="wrap-col">
								<div class="row">
									<div class="t-center" style="padding-top: 30px;">
										<div class="header">
											<h2>Salads:</h2>
										</div>
										<strong>BECIEGAST NVERITI VITAESAERT ASETY KERTYA ASET APLICA BOSERDE NERAFAE KERTYURAUAS VITAESA. </strong><br/><br>
										<span>Praesent vestibulum aenean nonummy endrerit mauris. Cum sociis natoque Magnis dis parturient montes. Ascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio gravida at cursus nec luctus a lorem.</span><br/><br>
										<a href="#" class="button" >More Details</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
				<!-----------------content-box-3-------------------->
				<section class="content-box background-gray box-3 zerogrid">
					<div class="row wrap-box"><!--Start Box-->
						<div class="col-1-2">
							<div class="wrap-col">
								<div style="padding-top: 60px;">
									<center><%= image_tag("1.png") %></center>
								</div>
							</div>
						</div>
						<div class="col-1-2">
							<div class="wrap-col">
								<div class="row">
									<div class="t-center" style="padding-top: 30px;">
										<div class="header">
											<h2>Grill menu:</h2>
										</div>
										<strong>BECIEGAST NVERITI VITAESAERT ASETY KERTYA ASET APLICA BOSERDE NERAFAE KERTYURAUAS VITAESA. </strong><br/><br>
										<span>Praesent vestibulum aenean nonummy endrerit mauris. Cum sociis natoque Magnis dis parturient montes. Ascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio gravida at cursus nec luctus a lorem.</span><br/><br>
										<a href="#" class="button" >More Details</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
				<!-----------------content-box-4-------------------->
				<section class="content-box boxstyle-2 box-4">
					<div class="zerogrid">
						<div class="row wrap-box"><!--Start Box-->
							<div class="header">
								<hr class="line-1">
								<h2 style="color: #fff;">Latest event:</h2>
							</div>
							<div class="post">
								<div class="col-1-2">
									<%= image_tag("event.jpg") %>
								</div>
								<div class="col-1-2">
									<div class="wrapper">
										<h3>The title on the article</h3>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam viverra convallis auctor. Sed accumsan libero quis mi commodo et suscipit enim lacinia. Morbi rutrum vulputate est sed faucibus.</p>
										<a class="button" href="#">Read More</a>
									</div>	
								</div>
							</div>
						</div>
					</div>
				</section>
				
			</div>
		</section>
		<hr class="line">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoodFood</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="wrap-body">

  	<header class="zerogrid">
		<div class="logo">
			<hr class="line-1">
			<%= link_to "GoodFood", root_path %>
			<span>Tasty food is great!</span>
			<hr class="line-1">
		</div>
		<div id='cssmenu' class="align-center">
			<ul>
			   <li class="active"><%= link_to "Home", root_path %></li>
			   <li class='last'><%= link_to "Contacts", new_contact_path %></li>
			</ul>
		</div>
	</header>

    <%= yield %>
    </div>
  </body>
</html>